Implement ga abstraction method & gtag.js embed
crdschurch/crds-media pull request #1028
Opened 2020-12-18 20:26 UTC by tcmacdonald

This PR implements an abstracted version of the `ga()` method so we can safely upgrade to gtag.js

2021-01-25 20:27 UTC, tcmacdonald commented on _includes/_head.html
> +
<!-- Global site tag (gtag.js) - Google Analytics -->
<script>
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-2977073-1');
</script>

2021-01-25 21:10 UTC, dholloran-ample requested changes
@mjvezzani I left 2 inline comments and also running locally it does not seem to update all of the `ga(` references. I tried both with the build plugin and just running the `grep` command

2021-01-26 02:26 UTC, mjvezzani commented on bin/substituteAnalyticsReferences.sh
> +grep -rl --exclude=\*.sh --exclude-dir=./.bundle --exclude-dir=./.jekyll-cache "ga('" . | xargs sed -i "s/ga('/abstractedAnalytics('/g"
So that is what I wanted to do, but when testing locally, using the `--include-dir` syntax with that `grep` command did not work. The command still searched through all directories. For whatever reason, however, the `--exclude-dir` command work without issue. If you know of a way to get the `--include-dir` flag to work property, I would love to make the change.

2021-01-26 11:49 UTC, mjvezzani commented on bin/substituteAnalyticsReferences.sh
> +grep -rl --exclude=\*.sh --exclude-dir=./.bundle --exclude-dir=./.jekyll-cache "ga('" . | xargs sed -i "s/ga('/abstractedAnalytics('/g"
Also, we are running the shell script after everything is built, so I presume we would also want to run the script against the built site directory? But because `--include-dir` doesn't seem to work, this will have to do for now.

2021-01-26 14:36 UTC, dholloran-ample commented on bin/substituteAnalyticsReferences.sh
> +grep -rl --exclude=\*.sh --exclude-dir=./.bundle --exclude-dir=./.jekyll-cache "ga('" . | xargs sed -i "s/ga('/abstractedAnalytics('/g"
Works for me.

2021-01-26 14:53 UTC, dholloran-ample approved these changes

2021-01-26 14:53 UTC, merged