US20513 Shows Landing Page
crdschurch/crds-media pull request #1067
Opened 2021-02-02 22:54 UTC by kellgauthier

## Task
Develops shows landing page per [design](https://projects.invisionapp.com/d/main#/console/20964701/441631718/preview). 
[Rally](https://rally1.rallydev.com/#/66096747656ud/custom/24109743995?detail=%2Fuserstory%2F483183596816) 

## Considerations 
- Jumbotron is a static image, will need to update with video background
- Data in int does not match design 
- Unsure where carousel images and recently added images are supposed to link to

2021-02-03 15:35 UTC, silasbaur requested changes
Let me know if you want to talk through anything
1. Everything is wrapped in `col-sm-10 col-sm-offset-1` but the design does not look like it calls for that
2. Remove arrows on the carousel if there are not more than 4 shows
3. Image does not line up
![Screen Shot 2021-02-03 at 10 27 25 AM](https://user-images.githubusercontent.com/32345656/106769888-73e51b00-660b-11eb-861b-7f5cf8e14234.png)
4. Take a look at mobile

2021-02-03 15:35 UTC, silasbaur commented on _assets/stylesheets/pages/_shows.scss
> +      width: 40%;
Not a fan of this. Lets just add a class of `col-sm-4` to the div with `jumbotron-content`.

2021-02-03 15:35 UTC, silasbaur commented on _assets/stylesheets/pages/_shows.scss
> +  margin-bottom: -9rem;
We do not need this. Change the layout to `default_footer_flush`

2021-02-03 15:35 UTC, silasbaur commented on _plugins/generators/shows_generator.rb
> +          testing = video.data['shows_episodes'] = site.collections['videos'].docs.select{ |doc| doc.data.dig('collections') }.flatten.uniq
We do not need `testing =` anymore. If we do need it we should not call this testing

2021-02-03 15:35 UTC, silasbaur commented on _includes/_shows-most-recent.html
> +</div>
(PICKY COMMENT INCOMING) Not a huge fan of how this set up. I think it is more readable if it is set up like this:
```
<div>
  <div>
    <img />
  </div>

  <div>
    {{ Content here }}
  </div>
</div>
```

2021-02-03 15:35 UTC, silasbaur commented on shows.html
> +        src="https://videos.ctfassets.net/y3a9myzsdjan/61UX4j16LJ4i6Hul1obi2Z/02c4498b9d0c1ef87fb7767fbfcaed54/spiritual-outfitters-loop.mp4"
Why is this here? Shouldn't this be a featured show episode?

2021-02-03 15:35 UTC, silasbaur commented on shows.html
> +  <div class="jumbotron jumbotron-xl bg-video inline-video jumbotron-home flush" style="text-align: left; background-image: url('//crds-media.imgix.net/4b1Vka2whxFu1JNjx9pckB/1d48c4bbc5399c597c39a81f
We should probably create a featured_media entry for this so that can be easily changed by content admins

2021-02-03 15:35 UTC, silasbaur commented on shows.html
> +              <crds-button href="#" color="white" icon="play-thin" icon-align="left" icon-color="blue" icon-size="14" text="Play"></crds-button>
This button needs to be able to play the video

2021-02-04 18:24 UTC, silasbaur requested changes
1. Everything is wrapped in `col-sm-10 col-sm-offset-1` but the design does not look like it calls for that
2. Image does not line up
![Screen Shot 2021-02-03 at 10 27 25 AM](https://user-images.githubusercontent.com/32345656/106769888-73e51b00-660b-11eb-861b-7f5cf8e14234.png)
3. Take a look at mobile.

2021-02-10 15:00 UTC, silasbaur requested changes
1. Inconsistant image sizes
![Screen Shot 2021-02-10 at 9 58 33 AM](https://user-images.githubusercontent.com/32345656/107527137-8bca1b00-6b86-11eb-896a-0194e8568a5f.png)
2. The play icon disappear after it is clicked. Is there a paused icon that can be used for when the button says pause?

2021-02-10 15:00 UTC, silasbaur commented on _assets/stylesheets/pages/_shows.scss
> +video {
Use a class

2021-02-10 15:46 UTC, kellgauthier commented
> 1. Inconsistant image sizes
>    ![Screen Shot 2021-02-10 at 9 58 33 AM](https://user-images.githubusercontent.com/32345656/107527137-8bca1b00-6b86-11eb-896a-0194e8568a5f.png)
> 2. The play icon disappear after it is clicked. Is there a paused icon that can be used for when the button says pause?

2021-02-10 16:09 UTC, silasbaur approved these changes

2021-02-10 16:10 UTC, silasbaur requested changes
![Screen Shot 2021-02-10 at 11 10 38 AM](https://user-images.githubusercontent.com/32345656/107537199-9db0bb80-6b90-11eb-9587-1848cdb33e46.png)

2021-02-10 18:50 UTC, silasbaur approved these changes

2021-02-10 18:50 UTC, merged