DE8161/Resolves shows feedback comments
crdschurch/crds-media pull request #1084
Opened 2021-02-15 23:42 UTC by kellgauthier

[Rally](https://rally1.rallydev.com/#/66096747656ud/custom/24109743995?detail=%2Fdefect%2F496977932712&fdp=true&previousTokens=%2F66096747656ud%2Fcustom%2F24109743995%3Fdetail%3D%252Fdefect%252F496977932712&ref=%2Fdefect%2F496977932712)
Preview

- [ ] The video up top should auto-play. It is not obvious to me that it's a video at first with the play button being on the bottom left of the banner. _**Google Chrome and other browsers will not allow a video to autoplay with sound. There are a few ways to accomplish a workaround with javascript, but it's not considered best UX**_
- [ ] I would imagine we would want a volume option _**See note above**_
- [x] Under the collection name should be the episode name in the jumbotron (in the design it's "Episode 24: Why do we have a garage?") to make it more clear that it's the most recent episode that is playing. Right now we say Garage Bible Study twice in a row in the jumbotron. 
- [x] Font for this should be a bit smaller like in the design
- [x] The Play button and the More Videos button should be bigger like the design. They are more noticeable that way.
- [x] More Videos button should link to the collection page for whatever collection is featured. 
- [x] In the design when you scroll over a show image in the carousel that card increases in size
- [x] The collections cards in the Shows carousel should click to that collection landing page
- [ ] Recently added should only be videos associated with a collection AND tagged as "feature on the shows landing page", right now I see student ministry collections videos but that is not a show. Content Administration issue with bad data on int.  _**This is a contentful / content management issue. Once the correct shows data is populated, it will display as anticipated in master. If warranted, I can delete what is currently in int for shows and recreate it to the design prior to merging this work into master**_
- [x] Recently added video thumbnails should be bigger like the design
- [x] The videos under recently added should be clickable.
- [x] The collection names in orange should be clickable to that collection landing page

Mobile 

- [x] The video is way cropped in on mobile vs the design
- [x] Play and More Videos buttons should be bigger like in the design
- [x] There is a fade to black from the video to the "Shows" Section in the design vs a clear line break

How are we going to do mousing over in mobile the carousel cards to bring up the description, because clicking should take you to the collection landing page?

2021-02-16 18:57 UTC, sarahshiffman commented
Hey Kell, 

1. Can we move the episode title closer to the episode description?
2. The link for more videos will should go to /media/collections/[collection name] instead of using tags. We want them to fall on the collection landing page for each and not just a media page with tagged vidoes (i.e. /media/collections/garage-bible-study)
3. The shows cards still don't click anywhere? They should link to /media/collections/[collection name] like above!
4. The orange collection name links under Recently Added should /media/collections/[collection name] instead of using tags. 
5. We still need to see the collection description over the shows cards on mobile? Can we make it so that when you are on a square it animates and shows the description? Then when you scroll right the one to left scales back down without description text and the one on the screen scales up with description?

2021-02-18 21:24 UTC, dholloran-ample requested changes
@kellgauthier - Left a few inline comments about building up the URLs. Let me know if you have any questions.

2021-02-18 21:24 UTC, dholloran-ample commented on _includes/_shows-most-recent.html
> +    <a href="{{ site.url }}/media/videos/{{ episode.slug }}">
I think you may be able to get the Episode's URL via `episode. permalink`. If you can let's use that instead of building up the URL.

2021-02-18 21:24 UTC, dholloran-ample commented on _includes/_shows-most-recent.html
> +    <a href="{{ site.url }}/media/collections/{{ show.slug }}">
I think you may be able to get the Shows' URL via `show. permalink`. If you can let's use that instead of building up the URL.

2021-02-18 21:24 UTC, dholloran-ample commented on shows.html
> +                <a href="{{ site.url }}/media/collections{{ shows.slug }}"><button class="more-videos btn btn-white btn-outline">More Videos</button></a>
See the previous comment about `shows.permalink`

2021-02-18 21:24 UTC, dholloran-ample commented on shows.html
> +    <div class="row soft-bottom push-bottom carousel-shows">
See the previous comment about `shows.permalink`

2021-02-19 15:35 UTC, kellgauthier commented on _includes/_shows-most-recent.html
> +    <a href="{{ site.url }}/media/collections/{{ show.slug }}">
`{{ show.permalink }}` did not result in the correct url. Same as the other suggestions.

2021-02-19 15:36 UTC, kellgauthier commented
Per direction from AG:

- add play button per design but title it "watch now" 
- remove play/pause button 
- keep mute/unmute button and make it smaller

2021-02-22 21:35 UTC, kellgauthier commented
Direction from client - move shows carousel up closer to the jumbotron

2021-02-24 16:14 UTC, tcmacdonald commented on _assets/javascripts/components/shows-video-player.js
> +const display = 'icon-video';
I would recommend _not_ using ES6 keywords or features if you're not transpiling or using a module bundler. It's probably fine but you never know if somebody on IE11 will run into issues.

2021-02-24 16:50 UTC, tcmacdonald commented
Couple more issues to consider. Also, triple check the state of the carousel and alignment of certain items (mute icon, for example) on small screens. Its a little rough depending on the size of the viewport. 

<img width="829" alt="Crossroads_Media" src="https://user-images.githubusercontent.com/50378/109035185-6107b880-7696-11eb-877e-13235326e7d8.png">

2021-02-24 16:51 UTC, tcmacdonald approved these changes

2021-02-25 13:33 UTC, merged